"""Every approved rule ships with a test that proves it still fires.

The loop is only closed if the rule survives the next refactor. So approving a
bundle also writes a pytest file: one test per rule, asserting the content gate
blocks that rule's sample — and one test asserting the bundle still verifies.

Generated tests are ordinary files, committed like any other. They are not
magic: if a rule is later withdrawn, its test is deleted with it, and the diff
says so.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

_HEADER = '''"""AUTO-GENERATED from rule bundle {bundle_id!r} — approved by {approved_by!r}.

Regenerated by `al learn approve`. Each test pins one learned rule to the
sample that taught it: if a refactor stops the gate blocking that payload, the
rule silently regressed and this fails. Do not hand-edit; withdraw the rule
instead.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from al_core.config import load_settings
from al_core.detect import ContentGate
from al_core.detect.scanners import default_scanners
from al_core.learn.bundle import load_bundle
from al_core.learn.scanner import LearnedScanner
from al_verify.verify import load_public_key

BUNDLE = Path(r"{bundle_path}")
PUBKEY = Path(r"{pubkey_path}")


@pytest.fixture(scope="module")
def gate() -> ContentGate:
    """The real pipeline with the learned rules loaded from the SIGNED bundle."""
    pytest.importorskip("al_core")
    if not BUNDLE.exists() or not PUBKEY.exists():
        pytest.skip("rule bundle or public key not present in this checkout")
    doc = load_bundle(BUNDLE, load_public_key(PUBKEY.read_bytes()))
    settings = load_settings(None, admin_api_token="test")
    scanners = [*default_scanners(settings), LearnedScanner(doc["rules"])]
    return ContentGate(scanners, mode=settings.mode)


def test_bundle_still_verifies() -> None:
    if not BUNDLE.exists() or not PUBKEY.exists():
        pytest.skip("rule bundle or public key not present in this checkout")
    doc = load_bundle(BUNDLE, load_public_key(PUBKEY.read_bytes()))
    assert doc["bundle_id"] == {bundle_id!r}
    assert len(doc["rules"]) == {rule_count}

'''

_CASE = '''
def test_{slug}(gate: ContentGate) -> None:
    """{rationale}"""
    result = gate.scan_text({sample!r})
    assert result.verdict == {action!r}, (
        "learned rule {rule_id!r} regressed: the sample is no longer {action}ed")
    assert any(f["rule_id"] == {rule_id!r} for f in result.findings)
'''


def _slug(rule_id: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in rule_id).strip("_").lower()


def generate_tests(
    bundle: dict[str, Any],
    *,
    bundle_path: Path,
    pubkey_path: Path,
    out_dir: Path,
) -> Path:
    """Write the regression suite for a bundle. Returns the file path."""
    body = _HEADER.format(
        bundle_id=bundle["bundle_id"],
        approved_by=bundle["approved_by"],
        bundle_path=str(bundle_path.resolve()),
        pubkey_path=str(pubkey_path.resolve()),
        rule_count=len(bundle["rules"]),
    )
    for rule in bundle["rules"]:
        body += _CASE.format(
            slug=_slug(rule["rule_id"]),
            rationale=f"learned rule {rule['rule_id']} must keep firing",
            sample=rule.get("sample") or rule["pattern"],
            action=rule.get("action", "block"),
            rule_id=rule["rule_id"],
        )

    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"test_learned_{_slug(bundle['bundle_id'])}.py"
    path.write_text(body, encoding="utf-8")
    return path


__all__ = ["generate_tests"]
